# Generated by Django 4.2 on 2023-06-10 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Restauracja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('lokalizacja', models.CharField(max_length=100)),
                ('liczba_miejsc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rezerwacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('liczba_osob', models.IntegerField()),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lets_sit_together_4.klient')),
                ('restauracja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lets_sit_together_4.restauracja')),
            ],
        ),
        migrations.CreateModel(
            name='Klient_Restauracja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lets_sit_together_4.klient')),
                ('restauracja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lets_sit_together_4.restauracja')),
            ],
        ),
    ]
